// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc620.SwagRobot;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainMotorLF, driveTrainMotorLB, driveTrainMotorRF, driveTrainMotorRB;
    public static RobotDrive driveTrainRobotDrive21;
    public static AnalogChannel drivePIDdistanceSensor;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainMotorLF = new Jaguar(1, 2);
	LiveWindow.addActuator("DriveTrain", "MotorL", (Jaguar) driveTrainMotorLF);
        
        driveTrainMotorRF = new Jaguar(1, 1);
	LiveWindow.addActuator("DriveTrain", "MotorR", (Jaguar) driveTrainMotorRF);
        
        driveTrainMotorLB = new Jaguar(1, 4);
	LiveWindow.addActuator("DriveTrain", "MotorR", (Jaguar) driveTrainMotorRF);
        
        driveTrainMotorRB = new Jaguar(1, 3);
	LiveWindow.addActuator("DriveTrain", "MotorR", (Jaguar) driveTrainMotorRF);
        
        driveTrainRobotDrive21 = new RobotDrive(driveTrainMotorLF, driveTrainMotorLB, driveTrainMotorRF, driveTrainMotorRB);
	
        driveTrainRobotDrive21.setSafetyEnabled(true);
        driveTrainRobotDrive21.setExpiration(0.1);
        driveTrainRobotDrive21.setSensitivity(0.5);
        driveTrainRobotDrive21.setMaxOutput(1.0);
        
        drivePIDdistanceSensor = new AnalogChannel(1, 2);
	LiveWindow.addSensor("drivePID", "distanceSensor", drivePIDdistanceSensor);
        
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
