
package org.usfirst.frc620.SwagRobot.commands;
import edu.wpi.first.wpilibj.AnalogChannel;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc620.SwagRobot.Robot;
import org.usfirst.frc620.SwagRobot.RobotMap;
import org.usfirst.frc620.SwagRobot.OI;
import edu.wpi.first.wpilibj.Joystick;
import org.usfirst.frc620.SwagRobot.subsystems.DriveTrain;
/**
 *
 */
public class  DriveWithJoysticks extends Command {
    private Joystick joystickL;
    private AnalogChannel distanceSensor = RobotMap.drivePIDdistanceSensor;
    public DriveWithJoysticks() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveTrain);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    
    
    // Called just before this Command runs the first time
    protected void initialize() {
        
        joystickL = Robot.oi.getJoystickL();
        
    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        double x = joystickL.getTwist();
        System.out.println("joystickL.getTwist "+joystickL.getTwist());
        if(Math.abs(joystickL.getTwist())<=0.5)
            x=0;
        else
            x=joystickL.getTwist();
        
        double d = distanceSensor.getVoltage()/(0.0098);
        System.out.println("Voltage: "+d);
        
        if(d >= 20)
        
        {
           Robot.driveTrain.mecanumDrive(.75*joystickL.getX(),.5*x,.75* joystickL.getY(), 0);
        }
        else{
            if(joystickL.getY()>=0){
                Robot.driveTrain.mecanumDrive(0,0,.75*joystickL.getY(),0);
            }
            else{
                Robot.driveTrain.mecanumDrive(0,0,0,0);
            }
        }
        
        //        Robot.driveTrain.setSpeed(joystickL.getX(), joystickL.getY());


//        System.out.println("Joystick: " + joystickL.getX() + ", " + joystickL.getY() + ", " + joystickL.getTwist());
//        System.out.println("L: " + Robot.driveTrain.getL() + " R: " + Robot.driveTrain.getR());
        
       
    }
        
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }
    // Called once after isFinished returns true
    protected void end() {
    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
