// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc620.SwagRobot.subsystems;
import org.usfirst.frc620.SwagRobot.RobotMap;
import org.usfirst.frc620.SwagRobot.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
/**
 *
 */
public class DriveTrain extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController motorL = RobotMap.driveTrainMotorLF;
    SpeedController motorR = RobotMap.driveTrainMotorRF;
    RobotDrive robotDrive21 = RobotMap.driveTrainRobotDrive21;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new DriveWithJoysticks());
        //setDefaultCommand(new Autonomous());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
/*    
    public void setSpeed(double speedR, double speedL)
    {
      robotDrive21.tankDrive(speedR, speedL);
    }
    */
    public void mecanumDrive(double x, double y, double z, double gyro)
    {
        
        robotDrive21.mecanumDrive_Cartesian(x, y, z, gyro);
        
        System.out.println("mecanumDrive: x=" + x + ", y=" + y + ", z=" + z);
    }
    public double getL() {
        return motorL.get();
    }
    public double getR() {
        return motorR.get();
    }
}
